ALTER TABLE `mw_db_version`
    DROP COLUMN `entry`, 
    DROP PRIMARY KEY;

INSERT INTO `mw_db_version` VALUES ('4.0.9', UNIX_TIMESTAMP());

DROP TABLE IF EXISTS `mw_config`;

CREATE TABLE `mw_config`(  
  `site_title` VARCHAR(64) DEFAULT 'MaNGOS Web V4',
  `site_email` VARCHAR(64) DEFAULT 'admin@mistvale.com',
  `site_cookie` VARCHAR(255) DEFAULT 'MaNGOSWebV4',
  `site_href` VARCHAR(255) DEFAULT '/',
  `site_base_href` VARCHAR(255) DEFAULT 'http://www.mistvale.com',
  `site_armory` VARCHAR(32) DEFAULT 'http://realmplayers.com',
  `site_forums` VARCHAR(32) DEFAULT '/forum/',
  `emulator` VARCHAR(32) DEFAULT 'mangos',
  `templates` VARCHAR(255) DEFAULT 'WotLK,Cataclysm_1,illidan,sunwell,Mists_of_Pandaria_v1.0,Burning_Crusade',
  `default_lang` VARCHAR(32) DEFAULT 'English',
  `available_lang` VARCHAR(255) DEFAULT 'English',
  `reg_allow` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `reg_require_activation` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `reg_require_invite` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `reg_require_recaptcha` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `reg_recaptcha_private_key` VARCHAR(64),
  `reg_recaptcha_public_key` VARCHAR(64),
  `reg_require_secret_questions` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `allow_user_pass_change` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `allow_user_email_change` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `max_account_per_ip` TINYINT UNSIGNED NOT NULL DEFAULT 10,
  `default_component` VARCHAR(64) DEFAULT 'frontpage',
  `flash_display_type` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `fp_vote_banner` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `fp_newbie_guide` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `fp_hitcounter` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `fp_server_info` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `fp_realm_status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `fp_players_online` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `fp_server_ip` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `fp_server_type` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `fp_server_pop` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `fp_server_lang` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `fp_server_act` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `fp_server_active_act` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `fp_server_chars` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `fp_server_more_info` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `email_type` TINYINT UNSIGNED NOT NULL DEFAULT 2,
  `email_smtp_host` VARCHAR(64) DEFAULT 'smtp.gmail.com',
  `email_smtp_port` SMALLINT UNSIGNED NOT NULL DEFAULT 465,
  `email_use_secure` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `email_smtp_secure` VARCHAR(32) NOT NULL DEFAULT 'SSL',
  `email_smtp_user` VARCHAR(64),
  `email_smtp_pass` VARCHAR(64),
  `paypal_email` VARCHAR(64) DEFAULT 'admin@mistvale.com',
  `site_notice_enable` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `module_online_list` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `module_fp_ssotd` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `module_vote_system` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `module_vote_online_check` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `module_news_items` TINYINT UNSIGNED NOT NULL DEFAULT 10,
  `module_news_open` TINYINT UNSIGNED NOT NULL DEFAULT 3,
  `module_char_rename` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `module_char_rename_pts` TINYINT UNSIGNED NOT NULL DEFAULT 2,
  `module_char_customize` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `module_char_customize_pts` TINYINT UNSIGNED NOT NULL DEFAULT 5,
  `module_char_faction_change` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `module_char_faction_change_pts` TINYINT UNSIGNED NOT NULL DEFAULT 15,
  `module_char_race_change` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `module_char_race_change_pts` TINYINT UNSIGNED NOT NULL DEFAULT 10,
  `enable_debugging` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `default_realm_id` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `db_logon_host` VARCHAR(32) NOT NULL DEFAULT '127.0.0.1',
  `db_logon_port` SMALLINT UNSIGNED NOT NULL DEFAULT 3306,
  `db_logon_name` VARCHAR(32) NOT NULL DEFAULT '',
  `db_logon_user` VARCHAR(64) NOT NULL DEFAULT '',
  `db_logon_pass` VARCHAR(64) NOT NULL DEFAULT ''
) ENGINE=MYISAM CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO mw_config () VALUES ();

DROP TABLE IF EXISTS `mw_realm`;

CREATE TABLE `mw_realm` (
  `realm_id` INT UNSIGNED NOT NULL,
  `site_enabled` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `db_world_host` VARCHAR(32) DEFAULT '127.0.0.1',
  `db_world_port` SMALLINT UNSIGNED DEFAULT 3306,
  `db_world_name` VARCHAR(32) DEFAULT '',
  `db_world_user` VARCHAR(64) DEFAULT '',
  `db_world_pass` VARCHAR(64) DEFAULT '',
  `db_char_host` VARCHAR(32) DEFAULT '127.0.0.1',
  `db_char_port` SMALLINT UNSIGNED DEFAULT 3306,
  `db_char_name` VARCHAR(32) DEFAULT '',
  `db_char_user` VARCHAR(64) DEFAULT '',
  `db_char_pass` VARCHAR(64) DEFAULT '',
  `ra_type` TINYINT UNSIGNED DEFAULT 0,
  `ra_port` SMALLINT UNSIGNED DEFAULT 3443,
  `ra_user` VARCHAR(64) DEFAULT '',
  `ra_pass` VARCHAR(64) DEFAULT '',
  PRIMARY KEY (`realm_id`)
) ENGINE=MYISAM CHARSET=utf8 COLLATE=utf8_unicode_ci;
